footprint: [[-0.275, 0.419], [0.275, 0.419], [0.275, -0.419], [-0.275, -0.419]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05


# layer definitions
static:
  map_topic: /map
  subscribe_to_updates: true

obstacles_layer:
  max_obstacle_height: 999.0
  min_obstacle_height: -999.0
  obstacle_range: 5.5
  raytrace_range: 6.0
  observation_sources: laser
  laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

inflation:
  inflation_radius: 1.0